### ISSUE TITLE
Error with label value when assembly with 6502

### ISSUE THREAD

**Issue by DoctorWho406** [rdeioris/necroassembler#1]
Hi,
I am trying to compile my file written for 6502 with the necroassembler
```
necro_6502.exe Assemblyes/6502/Snake/Snake.S Assemblyes/6502/Snake/Snake.bin
```

but every time I issue the command I get this error message:

>Traceback (most recent call last):
  File "C:\Users\lollo\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\lollo\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Documents\AIV\III Anno\venv\Scripts\necro_6502.exe\__main__.py", line 7, in <module>
  File "D:\Documents\AIV\III Anno\venv\lib\site-packages\necroassembler\assembler.py", line 825, in main
    asm.link()
  File "D:\Documents\AIV\III Anno\venv\lib\site-packages\necroassembler\assembler.py", line 261, in link
    self._resolve_labels()
  File "D:\Documents\AIV\III Anno\venv\lib\site-packages\necroassembler\assembler.py", line 237, in _resolve_labels
    raise NotInBitRange(true_address, total_bits, label)
necroassembler.exceptions.NotInBitRange: label "game" with value -130 is not in the 8 bit range

This is [my file](https://github.com/DoctorWho406/6502_Snake/blob/main/Snake.S)

I noticed that if I delete 3 lines of code (apparently at random) the error disappears

Any advice?

**Comment by rdeioris** [comment]
Branches have 8 bits offset. You cannot jump higher than 127 bytes and lower than -128. You need to restructure your code for respecting this limit

**Comment by DoctorWho406** [comment]
Ok,
so if you move lines 115 to 118 to line 28 should it work?

Thank you so much

**Comment by ldo** [comment]
This is why you need to understand the quirks of the machine that you are writing assembly language for. Nothing is hidden from you!
